spring.application.name=nmaravic-movie-api
# base path for all API endpoints
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}
# database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=false
spring.flyway.schemas=public
# pagination
movie.page.size=${MOVIE_PAGE_SIZE}
movie.top.rated.limit=${MOVIE_TOP_RATED_LIMIT}
# file upload
movie.image.upload.dir=${MOVIE_IMAGE_UPLOAD_DIR}
movie.image.server.base.url=${MOVIE_IMAGE_SERVER_BASE_URL}
# security
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI}
# rate limiting
rate.limit.authenticated=100
rate.limit.anonymous=20
# actuator
management.server.port=8081
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
# swagger/openapi
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html